### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by UnEnanoMas** [mmm545/PacketLogger#1]
Add + info <3

**Comment by mmm545** [comment]
:D

**Comment by mmm545** [comment]
wdym

**Comment by UnEnanoMas** [comment]
What does this plugin do

**Comment by mmm545** [comment]
Oh
It basically logs received and sent packets to a file, maybe it's useful if u want to check if a certain packet was sent/received

**Comment by UnEnanoMas** [comment]
Oh thank you very much for explaining, you should put it in the plugin information so that people (silly like me) could understand it hahaha

**Comment by mmm545** [comment]
Yea probably adding README.md tommorow :D
