### ISSUE TITLE
Killed Server...

### ISSUE THREAD

**Issue by i3rain** [mmm545/PacketLogger#2]
This Plugin creates a Log File named „/packets.log“...
This File cant delete or Change!
Now the Server is Killed and dont start, the File has a reached Size of 2000000000 GB.

**Comment by mmm545** [comment]
Oops
I will add a file size limit in the next update
I will keep the issue open until i fix it
Also did you download it without any reason without knowing what it does, it's literally in the "Developer tools" category

**Comment by i3rain** [comment]
I know it, the first days ist all Good with this Plugin. 
But on one day, the Size has grown from 1GB to 2 Million of GB.
Fix it please, before other Users need to destroy his Server, because the File cant delete.

Have a good day

**Comment by mmm545** [comment]
well... 880a609
